### PR TITLE
fix: make ChangesetName optional #112

### PR DESCRIPTION
**Pull request by chefren**
*Issue #112*

*Description of changes:*

Made ChangesetName optional.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by chefren** [comment]
@kddejong @MeroFuruya please review when possible.

**Comment by josealdaco** [comment]
I think its worth adding in the code snippet from [here](https://github.com/aws-actions/aws-cloudformation-github-deploy/commit/15936c7760eabad905250f6660ef08cd2c0cb08b#commitcomment-131601028) to this pr and including a `changeSetName` parameter to `deployStack` instead of an or condition. 

`deploy.ts`
```
export async function deployStack(
  cfn: aws.CloudFormation,
  params: CreateStackInput,
  changeSetName: string,
  noEmptyChangeSet: boolean,
  ...
  
  return await updateStack(
    cfn,
    stack,
    {
      ChangeSetName: changeSetName,
      ...{
        StackName: params.StackName,
        ...
  

```

**Comment by MeroFuruya** [comment]
> @kddejong @MeroFuruya please review when possible.

i mean i obviously did some really nasty stuff there, sorry for that ._.

but i guess you should at least make all the tests run green 👀

**Comment by kddejong** [comment]
Whats the goal on this one?  I agree with the changes that @josealdaco has done.  Let me know if you can get that done and I'll get it merged and released

**Pull request closed without merging**
