### PR TITLE
Adding ability to have comma delimited values within quotes for parameter-verrides.

### PR DESCRIPTION
**Pull request by timharris777**
*Issue #, if available:*
#47 

*Description of changes:*
Updated src/utils.ts so that it properly accepts comma separated values within quotes for parameter-overrides. An example would be to pass in a list of subnets.

I confirmed all tests are passing and that the code works.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by timharris777** [comment]
@katallaxie, can someone take a look at this pull request? We would like to stop use your official version as opposed to maintaining our forked version.

**Comment by Sunilsbcloud** [comment]
@katallaxie, or anyone please look into this PR, this looks to be an important feature and affecting many scenarios.

**Comment by timharris777** [comment]
Quick update, I spoke to our AWS rep and they are trying to identify a new owner for this repo.

**Comment by rvdbogerd** [comment]
We have the same issue, the fix is looking good. let's merge it, shall we?

**Comment by monemihir** [comment]
Noooo why was this closed, I really need this to be merged in :(

**Comment by paulvav** [comment]
Bump - also need this please!

**Comment by kddejong** [comment]
I will pick this up this week and see if we can get it out there.

**Comment by kddejong** [comment]
Worth noting that you can do this as follows:
`MyParam1=myValue1,MyParam2=myValue2,MyParam2=myValue3`

https://github.com/aws-actions/aws-cloudformation-github-deploy/blob/87a972c53e8e3eba056d472b9579c2cd584be99a/__tests__/utils.test.ts#L59-L73

We could look at changing this but does this fix the issue you are having?

**Pull request closed without merging**
