### PR TITLE
Remove duplicate file:// declaration in parameter-overrides docs

### PR DESCRIPTION
**Pull request by robd**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sanjP10** [comment]
Can we also remove ```${{ github.workspace }}```

It seems to be causing issues with github action workflows when pulling master
```
Download action repository 'actions/checkout@v2'
Download action repository 'aws-actions/configure-aws-credentials@v1'
Download action repository 'aws-actions/aws-cloudformation-github-deploy@master'
Error: aws-actions/aws-cloudformation-github-deploy/master/action.yml (Line: 18, Col: 18):
Error: aws-actions/aws-cloudformation-github-deploy/master/action.yml (Line: 18, Col: 18): Unrecognized named-value: 'github'. Located at position 1 within expression: github.workspace
Error: Fail to load aws-actions/aws-cloudformation-github-deploy/master/action.yml
```

**Comment by robd** [comment]
Hi @sanjP10 

Thanks for your message. I wasn't able to see the build which failed - could you point me at this and I will take a look? Just to confirm - the error you're seeing is in the current master build, not related to this PR?

I'm keen to keep the documentation in there about how to use a local file for `parameter-overrides` if possible since this was very helpful when setting this up.

https://github.com/newrelic/deployment-marker-action/pull/7 fixed this sort of docs issue for the deployment-marker-action project, so perhaps we could do something like this if I can reproduce the problem?

**Comment by sanjP10** [comment]
> Hi @sanjP10
> 
> Thanks for your message. I wasn't able to see the build which failed - could you point me at this and I will take a look? Just to confirm - the error you're seeing is in the current master build, not related to this PR?
> 
> I'm keen to keep the documentation in there about how to use a local file for `parameter-overrides` if possible since this was very helpful when setting this up.
> 
> [newrelic/deployment-marker-action#7](https://github.com/newrelic/deployment-marker-action/pull/7) fixed this sort of docs issue for the deployment-marker-action project, so perhaps we could do something like this if I can reproduce the problem?

Hi,

Yes this is in relation to master, I don't have an example that you can take a look at, as its on a private repository, but essentially I have this as my step, but when the job tries to setup, I get the logs that are shown in my original reply. 

Looking at it it seems something like you saw in [newrelic/deployment-marker-action#7](https://github.com/newrelic/deployment-marker-action/pull/7), so maybe this can be done later.

```
      - name: Deploy VPC
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: <name>
          template: <yaml file>
          no-fail-on-empty-changeset: 1
```

**Comment by ryanbtraveltek** [comment]
I'm also having the same issue as @sanjP10 
Seems to be directly related to the `${{ github.workspace }}` Once thats removed it works fine, switching to v1 rather than master also works.

**Pull request merged**
